/**
 * Export tool domain: export_project, list_export_presets, check_export_readiness.
 *
 * export_project uses execGodot directly (NOT runOperation) since
 * Godot export is a CLI operation (--export-release / --export-debug flag),
 * not a godot_operations.gd dispatch. Its bespoke stderr/stdout pattern
 * failure detection is intentional (Godot exits 0 on export failure).
 * Extended 180s timeout for export builds.
 *
 * list_export_presets and check_export_readiness parse export_presets.cfg /
 * project.godot locally using the same INI parser used for project.godot.
 * There are no runOperation/executeOperation call sites in this module.
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { join } from 'path';
import { existsSync, readFileSync } from 'fs';
import type { ServerContext } from '../types.js';
import { execGodot, resolveWithinProject, validatePath } from '../godot.js';
import { toolError } from '../errors.js';
import { parseProjectSettings } from '../parsers/project-parser.js';

/**
 * Parse export_presets.cfg and extract preset metadata.
 * Strips surrounding quotes from name and platform values.
 * Only matches top-level preset sections (preset.0, preset.1) — not
 * nested option sections (preset.0.options).
 */
function parseExportPresets(
  projectPath: string,
): Array<{ name: string; platform: string; runnable: boolean }> {
  const cfgPath = join(projectPath, 'export_presets.cfg');
  if (!existsSync(cfgPath)) return [];
  const content = readFileSync(cfgPath, 'utf-8');
  const parsed = parseProjectSettings(content);
  const presets: Array<{ name: string; platform: string; runnable: boolean }> = [];
  for (const section of Object.keys(parsed.sections)) {
    // Match sections like "preset.0", "preset.1" (not "preset.0.options")
    if (/^preset\.\d+$/.test(section)) {
      const s = parsed.sections[section];
      if (s.name) {
        presets.push({
          name: s.name.replace(/^"|"$/g, ''),
          platform: (s.platform || '').replace(/^"|"$/g, ''),
          runnable: s.runnable === 'true',
        });
      }
    }
  }
  return presets;
}

export function registerExportTools(server: McpServer, ctx: ServerContext): void {
  // Tool: export_project (EXPT-01, EXPT-02)
  server.registerTool(
    'export_project',
    {
      title: 'Export Project',
      description:
        'Export a Godot project headlessly for a named export preset. Validates that export_presets.cfg exists and the preset name is defined before invoking Godot. Uses a 180-second timeout for large projects.',
      inputSchema: {
        project_path: z.string().describe('Path to the Godot project directory'),
        preset_name: z
          .string()
          .describe("Name of the export preset (e.g., 'Web', 'Linux')"),
        output_path: z
          .string()
          .describe(
            "Relative path for the exported output file (e.g., 'build/web/index.html')",
          ),
        mode: z
          .enum(['release', 'debug'])
          .optional()
          .default('release')
          .describe("Export mode: 'release' (default) or 'debug'"),
      },
    },
    async ({ project_path, preset_name, output_path, mode }) => {
      if (!validatePath(project_path as string)) {
        return toolError('Invalid path', [
          'Provide valid paths without ".." or other potentially unsafe characters',
        ]);
      }

      try {
        const projectFile = join(project_path as string, 'project.godot');
        if (!existsSync(projectFile)) {
          return toolError(`Not a valid Godot project: ${project_path}`, [
            'Ensure the path points to a directory containing a project.godot file',
            'Use list_projects to find valid Godot projects',
          ]);
        }

        // Pre-flight validation: export_presets.cfg must exist (EXPT-02)
        const cfgPath = join(project_path as string, 'export_presets.cfg');
        if (!existsSync(cfgPath)) {
          return toolError('export_presets.cfg not found in project directory', [
            'Create export presets in the Godot editor: Project > Export > Add...',
            'The file export_presets.cfg is generated by Godot when you configure export presets',
          ]);
        }

        // Pre-flight validation: preset name must exist in cfg (EXPT-02)
        const presets = parseExportPresets(project_path as string);
        const presetNames = presets.map((p) => p.name);
        if (!presetNames.includes(preset_name as string)) {
          return toolError(
            `Preset '${preset_name}' not found in export_presets.cfg`,
            [
              `Available presets: ${presetNames.join(', ')}`,
              'Use list_export_presets to see all configured presets',
            ],
          );
        }

        // Resolve the output path inside the project before passing it to Godot
        const fullOutputPath = resolveWithinProject(project_path as string, output_path as string);
        if (fullOutputPath === null) {
          return toolError('Invalid output_path: path resolves outside the project directory', [
            'Use a path relative to the project root',
            'Do not use "..", absolute paths, or symlinks that escape the project',
          ]);
        }

        // Build CLI args for Godot export
        const exportFlag =
          (mode as string) === 'debug' ? '--export-debug' : '--export-release';
        const args = [
          '--headless',
          '--path',
          project_path as string,
          exportFlag,
          preset_name as string,
          fullOutputPath,
        ];

        const { stdout, stderr } = await execGodot(ctx.godotPath, args, {
          timeout: 180_000,
        });

        // Post-flight validation: check for error strings in stdout
        // (Godot exits 0 even on export failure)
        if (stdout.includes('No export template found')) {
          return toolError('No export template found for this preset', [
            'Download export templates: Editor > Manage Export Templates > Download',
            'Ensure templates match your Godot version',
          ]);
        }
        if (stdout.includes('Preset not found')) {
          return toolError(`Export preset not found: ${preset_name}`, [
            'Use list_export_presets to see available presets',
            'Check that the preset name matches exactly (case-sensitive)',
          ]);
        }
        if (stdout.includes('Failed to')) {
          return toolError(`Export failed: ${stdout}`, [
            'Check the export preset configuration in the Godot editor',
            'Verify that all required resources are present',
          ]);
        }

        // Also check stderr -- Godot may emit error strings there
        // even with exit code 0
        if (stderr) {
          const stderrTrimmed = stderr.trim();
          if (
            stderrTrimmed.includes('ERROR') ||
            stderrTrimmed.includes('Cannot open file') ||
            stderrTrimmed.includes('Failed to') ||
            stderrTrimmed.includes('Invalid')
          ) {
            return toolError(`Export failed (stderr): ${stderrTrimmed}`, [
              'Check the export preset configuration in the Godot editor',
              'Verify that all required resources and templates are present',
              'Use list_export_presets to verify preset configuration',
            ]);
          }
        }

        return {
          content: [
            {
              type: 'text' as const,
              text: JSON.stringify({
                success: true,
                preset: preset_name,
                output_path,
                mode: (mode as string) || 'release',
              }),
            },
          ],
        };
      } catch (error: unknown) {
        const errorMessage = error instanceof Error ? error.message : 'Unknown error';
        return toolError(`Export failed: ${errorMessage}`, [
          'Ensure Godot is installed correctly',
          'Check if the GODOT_PATH environment variable is set correctly',
          'For large projects, the 180-second timeout may not be sufficient',
        ]);
      }
    },
  );

  // Tool: list_export_presets (EXPT-03)
  server.registerTool(
    'list_export_presets',
    {
      title: 'List Export Presets',
      description:
        'List available export presets with names, platforms, and runnable status from export_presets.cfg. Parses the file locally for fast results without spawning Godot.',
      inputSchema: {
        project_path: z.string().describe('Path to the Godot project directory'),
      },
    },
    async ({ project_path }) => {
      if (!validatePath(project_path as string)) {
        return toolError('Invalid path', [
          'Provide valid paths without ".." or other potentially unsafe characters',
        ]);
      }

      try {
        const cfgPath = join(project_path as string, 'export_presets.cfg');
        if (!existsSync(cfgPath)) {
          return toolError('export_presets.cfg not found in project directory', [
            'Create export presets in the Godot editor: Project > Export > Add...',
            'The file export_presets.cfg is generated by Godot when you configure export presets',
          ]);
        }

        const presets = parseExportPresets(project_path as string);

        return {
          content: [
            {
              type: 'text' as const,
              text: JSON.stringify({ presets }),
            },
          ],
        };
      } catch (error: unknown) {
        const errorMessage = error instanceof Error ? error.message : 'Unknown error';
        return toolError(`Failed to list export presets: ${errorMessage}`, [
          'Ensure the export_presets.cfg file is readable',
          'Check if the project path is correct',
        ]);
      }
    },
  );

  // Tool: check_export_readiness
  server.registerTool(
    'check_export_readiness',
    {
      title: 'Check Export Readiness',
      description:
        'Validate a Godot project\'s configuration for mobile/web export readiness. Returns a pass/warn/fail report based on real lessons from production game development.',
      inputSchema: {
        project_path: z.string().describe('Path to the Godot project directory'),
        platform: z
          .enum(['android', 'ios', 'web', 'all'])
          .optional()
          .default('all')
          .describe("Target platform to check: 'android', 'ios', 'web', or 'all' (default)"),
      },
    },
    async ({ project_path, platform }) => {
      if (!validatePath(project_path as string)) {
        return toolError('Invalid path', [
          'Provide valid paths without ".." or other potentially unsafe characters',
        ]);
      }

      try {
        const projectFile = join(project_path as string, 'project.godot');
        if (!existsSync(projectFile)) {
          return toolError(`Not a valid Godot project: ${project_path}`, [
            'Ensure the path points to a directory containing a project.godot file',
            'Use list_projects to find valid Godot projects',
          ]);
        }

        const content = readFileSync(projectFile, 'utf-8');
        const parsed = parseProjectSettings(content);
        const targetPlatform = (platform as string) || 'all';

        const checks: Array<{ check: string; status: 'pass' | 'warn' | 'fail'; detail: string }> =
          [];

        const appliesTo = (...platforms: string[]) =>
          targetPlatform === 'all' || platforms.includes(targetPlatform);

        // (a) Renderer check — all platforms
        if (appliesTo('android', 'ios', 'web')) {
          const renderingSection = parsed.sections['rendering'] || {};
          const renderer = renderingSection['renderer/rendering_method'];
          if (renderer === 'gl_compatibility') {
            checks.push({
              check: 'Renderer',
              status: 'pass',
              detail: 'gl_compatibility — broadest device support',
            });
          } else {
            checks.push({
              check: 'Renderer',
              status: 'warn',
              detail: `Current: ${renderer || 'not set (defaults to forward_plus)'}. gl_compatibility recommended for broadest device support`,
            });
          }
        }

        // (b) Texture compression — android
        if (appliesTo('android')) {
          const renderingSection = parsed.sections['rendering'] || {};
          const etc2 = renderingSection['textures/vram_compression/import_etc2_astc'];
          if (etc2 === 'true') {
            checks.push({
              check: 'Texture compression (ETC2/ASTC)',
              status: 'pass',
              detail: 'ETC2/ASTC compression enabled',
            });
          } else {
            checks.push({
              check: 'Texture compression (ETC2/ASTC)',
              status: 'fail',
              detail: 'ETC2/ASTC compression required for Android',
            });
          }
        }

        // (c) Display orientation — android, ios
        if (appliesTo('android', 'ios')) {
          const displaySection = parsed.sections['display'] || {};
          const orientation = displaySection['window/handheld/orientation'];
          if (orientation) {
            const stripped = orientation.replace(/^"|"$/g, '');
            if (['portrait', 'reverse_portrait', 'sensor_portrait'].includes(stripped)) {
              checks.push({
                check: 'Display orientation',
                status: 'pass',
                detail: `Orientation set to ${stripped}`,
              });
            } else {
              checks.push({
                check: 'Display orientation',
                status: 'warn',
                detail: `Orientation is ${stripped}. Set to portrait for typical mobile games`,
              });
            }
          } else {
            checks.push({
              check: 'Display orientation',
              status: 'warn',
              detail: 'No orientation set — defaults to landscape',
            });
          }
        }

        // (d) Stretch mode — all platforms
        if (appliesTo('android', 'ios', 'web')) {
          const displaySection = parsed.sections['display'] || {};
          const stretchMode = displaySection['window/stretch/mode'];
          if (stretchMode) {
            const stripped = stretchMode.replace(/^"|"$/g, '');
            if (stripped === 'canvas_items' || stripped === 'viewport') {
              checks.push({
                check: 'Stretch mode',
                status: 'pass',
                detail: `Stretch mode set to ${stripped}`,
              });
            } else {
              checks.push({
                check: 'Stretch mode',
                status: 'warn',
                detail: `Stretch mode is ${stripped} — canvas_items recommended for responsive UI`,
              });
            }
          } else {
            checks.push({
              check: 'Stretch mode',
              status: 'warn',
              detail: 'No stretch mode configured — set to canvas_items for responsive UI',
            });
          }
        }

        // (e) Export presets exist
        const presets = parseExportPresets(project_path as string);
        if (presets.length === 0) {
          checks.push({
            check: 'Export presets',
            status: 'fail',
            detail: 'No export presets found — create them in Project > Export > Add...',
          });
        } else if (targetPlatform !== 'all') {
          const platformMap: Record<string, string> = {
            android: 'Android',
            ios: 'iOS',
            web: 'Web',
          };
          const platformName = platformMap[targetPlatform] || targetPlatform;
          const hasPreset = presets.some(
            (p) => p.platform.toLowerCase() === platformName.toLowerCase(),
          );
          if (hasPreset) {
            checks.push({
              check: 'Export presets',
              status: 'pass',
              detail: `Found export preset for ${platformName}`,
            });
          } else {
            checks.push({
              check: 'Export presets',
              status: 'fail',
              detail: `No export preset for ${platformName}. Available: ${presets.map((p) => p.platform).join(', ')}`,
            });
          }
        } else {
          checks.push({
            check: 'Export presets',
            status: 'pass',
            detail: `Found ${presets.length} export preset(s): ${presets.map((p) => p.platform).join(', ')}`,
          });
        }

        // (f) Audio format tip — all platforms
        checks.push({
          check: 'Audio format',
          status: 'warn',
          detail: 'Ensure audio uses OGG Vorbis (music) and WAV (SFX) — never MP3',
        });

        const summary = {
          pass: checks.filter((c) => c.status === 'pass').length,
          warn: checks.filter((c) => c.status === 'warn').length,
          fail: checks.filter((c) => c.status === 'fail').length,
        };

        return {
          content: [
            {
              type: 'text' as const,
              text: JSON.stringify({ platform: targetPlatform, checks, summary }),
            },
          ],
        };
      } catch (error: unknown) {
        const errorMessage = error instanceof Error ? error.message : 'Unknown error';
        return toolError(`Export readiness check failed: ${errorMessage}`, [
          'Ensure the project path is correct and project.godot is readable',
        ]);
      }
    },
  );
}
