/**
 * Export tool domain: export_project, list_export_presets.
 *
 * export_project uses execGodot directly (NOT executeOperation) since
 * Godot export is a CLI operation (--export-release / --export-debug flag),
 * not a GDScript script dispatch. Extended 180s timeout for export builds.
 *
 * list_export_presets parses export_presets.cfg locally using the
 * same INI parser used for project.godot.
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { join } from 'path';
import { existsSync, readFileSync } from 'fs';
import type { ServerContext } from '../types.js';
import { execGodot, validatePath } from '../godot.js';
import { toolError } from '../errors.js';
import { parseProjectSettings } from '../parsers/project-parser.js';

/**
 * Parse export_presets.cfg and extract preset metadata.
 * Strips surrounding quotes from name and platform values.
 * Only matches top-level preset sections (preset.0, preset.1) — not
 * nested option sections (preset.0.options).
 */
function parseExportPresets(
  projectPath: string,
): Array<{ name: string; platform: string; runnable: boolean }> {
  const cfgPath = join(projectPath, 'export_presets.cfg');
  if (!existsSync(cfgPath)) return [];
  const content = readFileSync(cfgPath, 'utf-8');
  const parsed = parseProjectSettings(content);
  const presets: Array<{ name: string; platform: string; runnable: boolean }> = [];
  for (const section of Object.keys(parsed.sections)) {
    // Match sections like "preset.0", "preset.1" (not "preset.0.options")
    if (/^preset\.\d+$/.test(section)) {
      const s = parsed.sections[section];
      if (s.name) {
        presets.push({
          name: s.name.replace(/^"|"$/g, ''),
          platform: (s.platform || '').replace(/^"|"$/g, ''),
          runnable: s.runnable === 'true',
        });
      }
    }
  }
  return presets;
}

export function registerExportTools(server: McpServer, ctx: ServerContext): void {
  // Tool: export_project (EXPT-01, EXPT-02)
  server.registerTool(
    'export_project',
    {
      title: 'Export Project',
      description:
        'Export a Godot project headlessly for a named export preset. Validates that export_presets.cfg exists and the preset name is defined before invoking Godot. Uses a 180-second timeout for large projects.',
      inputSchema: {
        project_path: z.string().describe('Path to the Godot project directory'),
        preset_name: z
          .string()
          .describe("Name of the export preset (e.g., 'Web', 'Linux')"),
        output_path: z
          .string()
          .describe(
            "Relative path for the exported output file (e.g., 'build/web/index.html')",
          ),
        mode: z
          .enum(['release', 'debug'])
          .optional()
          .default('release')
          .describe("Export mode: 'release' (default) or 'debug'"),
      },
    },
    async ({ project_path, preset_name, output_path, mode }) => {
      if (!validatePath(project_path as string)) {
        return toolError('Invalid path', [
          'Provide valid paths without ".." or other potentially unsafe characters',
        ]);
      }

      try {
        const projectFile = join(project_path as string, 'project.godot');
        if (!existsSync(projectFile)) {
          return toolError(`Not a valid Godot project: ${project_path}`, [
            'Ensure the path points to a directory containing a project.godot file',
            'Use list_projects to find valid Godot projects',
          ]);
        }

        // Pre-flight validation: export_presets.cfg must exist (EXPT-02)
        const cfgPath = join(project_path as string, 'export_presets.cfg');
        if (!existsSync(cfgPath)) {
          return toolError('export_presets.cfg not found in project directory', [
            'Create export presets in the Godot editor: Project > Export > Add...',
            'The file export_presets.cfg is generated by Godot when you configure export presets',
          ]);
        }

        // Pre-flight validation: preset name must exist in cfg (EXPT-02)
        const presets = parseExportPresets(project_path as string);
        const presetNames = presets.map((p) => p.name);
        if (!presetNames.includes(preset_name as string)) {
          return toolError(
            `Preset '${preset_name}' not found in export_presets.cfg`,
            [
              `Available presets: ${presetNames.join(', ')}`,
              'Use list_export_presets to see all configured presets',
            ],
          );
        }

        // Build CLI args for Godot export
        const exportFlag =
          (mode as string) === 'debug' ? '--export-debug' : '--export-release';
        const fullOutputPath = join(project_path as string, output_path as string);
        const args = [
          '--headless',
          '--path',
          project_path as string,
          exportFlag,
          preset_name as string,
          fullOutputPath,
        ];

        const { stdout } = await execGodot(ctx.godotPath, args, {
          timeout: 180_000,
        });

        // Post-flight validation: check for error strings in stdout
        // (Godot exits 0 even on export failure)
        if (stdout.includes('No export template found')) {
          return toolError('No export template found for this preset', [
            'Download export templates: Editor > Manage Export Templates > Download',
            'Ensure templates match your Godot version',
          ]);
        }
        if (stdout.includes('Preset not found')) {
          return toolError(`Export preset not found: ${preset_name}`, [
            'Use list_export_presets to see available presets',
            'Check that the preset name matches exactly (case-sensitive)',
          ]);
        }
        if (stdout.includes('Failed to')) {
          return toolError(`Export failed: ${stdout}`, [
            'Check the export preset configuration in the Godot editor',
            'Verify that all required resources are present',
          ]);
        }

        return {
          content: [
            {
              type: 'text' as const,
              text: JSON.stringify({
                success: true,
                preset: preset_name,
                output_path,
                mode: (mode as string) || 'release',
              }),
            },
          ],
        };
      } catch (error: unknown) {
        const errorMessage = error instanceof Error ? error.message : 'Unknown error';
        return toolError(`Export failed: ${errorMessage}`, [
          'Ensure Godot is installed correctly',
          'Check if the GODOT_PATH environment variable is set correctly',
          'For large projects, the 180-second timeout may not be sufficient',
        ]);
      }
    },
  );

  // Tool: list_export_presets (EXPT-03)
  server.registerTool(
    'list_export_presets',
    {
      title: 'List Export Presets',
      description:
        'List available export presets with names, platforms, and runnable status from export_presets.cfg. Parses the file locally for fast results without spawning Godot.',
      inputSchema: {
        project_path: z.string().describe('Path to the Godot project directory'),
      },
    },
    async ({ project_path }) => {
      if (!validatePath(project_path as string)) {
        return toolError('Invalid path', [
          'Provide valid paths without ".." or other potentially unsafe characters',
        ]);
      }

      try {
        const cfgPath = join(project_path as string, 'export_presets.cfg');
        if (!existsSync(cfgPath)) {
          return toolError('export_presets.cfg not found in project directory', [
            'Create export presets in the Godot editor: Project > Export > Add...',
            'The file export_presets.cfg is generated by Godot when you configure export presets',
          ]);
        }

        const presets = parseExportPresets(project_path as string);

        return {
          content: [
            {
              type: 'text' as const,
              text: JSON.stringify({ presets }),
            },
          ],
        };
      } catch (error: unknown) {
        const errorMessage = error instanceof Error ? error.message : 'Unknown error';
        return toolError(`Failed to list export presets: ${errorMessage}`, [
          'Ensure the export_presets.cfg file is readable',
          'Check if the project path is correct',
        ]);
      }
    },
  );
}
