/**
 * Scaffold tool domain: scaffold_event_bus
 *
 * Generates GDScript boilerplate files for common Godot patterns.
 * scaffold_event_bus creates a signal-only singleton for decoupled cross-system communication.
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { join, dirname } from 'path';
import { existsSync, writeFileSync, mkdirSync, readFileSync } from 'fs';
import type { ServerContext } from '../types.js';
import { runOperation, validatePath } from '../godot.js';
import { toolError } from '../errors.js';

/**
 * Convert a snake_case filename (without extension) to PascalCase.
 * e.g. "event_bus" -> "EventBus", "game_manager" -> "GameManager"
 */
function toPascalCase(snakeCase: string): string {
  return snakeCase
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/**
 * Extract the filename without extension from a path.
 * e.g. "scripts/autoloads/event_bus.gd" -> "event_bus"
 */
function filenameWithoutExtension(filePath: string): string {
  const base = filePath.split('/').pop() || filePath;
  const dotIndex = base.lastIndexOf('.');
  return dotIndex > 0 ? base.substring(0, dotIndex) : base;
}

export function registerScaffoldTools(server: McpServer, ctx: ServerContext): void {
  // scaffold_event_bus tool
  server.registerTool(
    'scaffold_event_bus',
    {
      title: 'Scaffold EventBus',
      description:
        'Generate a GDScript EventBus file — a signal-only singleton for decoupled cross-system communication. Optionally registers it as an autoload.',
      inputSchema: {
        project_path: z.string().describe('Path to the Godot project directory'),
        script_path: z
          .string()
          .describe(
            'Where to write the .gd file relative to project (e.g. "scripts/autoloads/event_bus.gd")',
          ),
        signals: z
          .array(
            z.object({
              name: z.string(),
              params: z
                .array(
                  z.object({
                    name: z.string(),
                    type: z.string(),
                  }),
                )
                .optional()
                .default([]),
            }),
          )
          .min(1)
          .describe('Signal definitions with typed parameters'),
        register_autoload: z
          .boolean()
          .optional()
          .default(false)
          .describe('Whether to also register as autoload in project.godot'),
        autoload_name: z
          .string()
          .optional()
          .describe(
            'Name for the autoload (default: derived from filename, PascalCase)',
          ),
      },
    },
    async ({ project_path, script_path, signals, register_autoload, autoload_name }) => {
      if (!validatePath(project_path) || !validatePath(script_path)) {
        return toolError('Invalid path', [
          'Provide valid paths without ".." or other potentially unsafe characters',
        ]);
      }

      try {
        const projectFile = join(project_path, 'project.godot');
        if (!existsSync(projectFile)) {
          return toolError(`Not a valid Godot project: ${project_path}`, [
            'Ensure the path points to a directory containing a project.godot file',
            'Use list_projects to find valid Godot projects',
          ]);
        }

        // Generate GDScript content
        const signalLines = signals.map((sig) => {
          if (sig.params.length === 0) {
            return `signal ${sig.name}`;
          }
          const paramStr = sig.params
            .map((p) => `${p.name}: ${p.type}`)
            .join(', ');
          return `signal ${sig.name}(${paramStr})`;
        });

        const gdscript = [
          '## EventBus — signal-only singleton for decoupled cross-system communication.',
          '## Generated by godot-mcp scaffold_event_bus tool.',
          '',
          'extends Node',
          '',
          ...signalLines,
          '',
        ].join('\n');

        // Create parent directories if they don't exist
        const fullPath = join(project_path, script_path);
        const parentDir = dirname(fullPath);
        if (!existsSync(parentDir)) {
          mkdirSync(parentDir, { recursive: true });
        }

        // Write the file
        writeFileSync(fullPath, gdscript, 'utf-8');

        // Optionally register as autoload
        const autoloadName =
          autoload_name || toPascalCase(filenameWithoutExtension(script_path));
        let autoloadRegistered = false;

        if (register_autoload) {
          const opResult = await runOperation(ctx, project_path, 'modify_project_setting', {
            section: 'autoload',
            key: autoloadName,
            value: '*res://' + script_path,
            action: 'set',
          });
          if (!opResult.ok) {
            return toolError(`Failed to register autoload: ${opResult.error}`, [
              'The script file was written, but autoload registration failed',
              'Verify the project path is accessible',
              'Check that Godot is installed and GODOT_PATH is set',
            ]);
          }
          autoloadRegistered = true;
        }

        const result = {
          success: true,
          script_path: script_path,
          signal_count: signals.length,
          autoload_registered: autoloadRegistered,
          ...(autoloadRegistered ? { autoload_name: autoloadName } : {}),
        };

        return {
          content: [
            {
              type: 'text' as const,
              text: JSON.stringify(result, null, 2),
            },
          ],
        };
      } catch (error: unknown) {
        const errorMessage =
          error instanceof Error ? error.message : 'Unknown error';
        return toolError(`Failed to scaffold EventBus: ${errorMessage}`, [
          'Ensure the project path is accessible',
          'Check that you have write permissions to the target directory',
          'Verify the script_path ends with .gd',
        ]);
      }
    },
  );

  // scaffold_config_manager tool
  server.registerTool(
    'scaffold_config_manager',
    {
      title: 'Scaffold ConfigManager',
      description:
        'Generate a ConfigFile-based persistence autoload GDScript. Creates setters that auto-save, plus load_data/save_data methods using ConfigFile.',
      inputSchema: {
        project_path: z.string().describe('Path to the Godot project directory'),
        script_path: z
          .string()
          .describe(
            'Where to write the .gd file relative to project (e.g. "scripts/autoloads/settings_manager.gd")',
          ),
        save_path: z
          .string()
          .describe('ConfigFile save path (e.g. "user://settings.cfg")'),
        sections: z
          .array(
            z.object({
              name: z.string(),
              fields: z.array(
                z.object({
                  name: z.string(),
                  type: z.string(),
                  default: z.string(),
                }),
              ),
            }),
          )
          .min(1)
          .describe('Config sections with typed fields and defaults'),
        register_autoload: z
          .boolean()
          .optional()
          .default(false)
          .describe('Whether to also register as autoload in project.godot'),
        autoload_name: z
          .string()
          .optional()
          .describe(
            'Name for the autoload (default: derived from filename, PascalCase)',
          ),
      },
    },
    async ({ project_path, script_path, save_path, sections, register_autoload, autoload_name }) => {
      if (!validatePath(project_path as string) || !validatePath(script_path as string)) {
        return toolError('Invalid path', [
          'Provide valid paths without ".." or other potentially unsafe characters',
        ]);
      }

      try {
        const projectFile = join(project_path as string, 'project.godot');
        if (!existsSync(projectFile)) {
          return toolError(`Not a valid Godot project: ${project_path as string}`, [
            'Ensure the path points to a directory containing a project.godot file',
            'Use list_projects to find valid Godot projects',
          ]);
        }

        // Flatten all fields from all sections for var declarations
        const allFields: { section: string; name: string; type: string; default: string }[] = [];
        for (const section of sections as { name: string; fields: { name: string; type: string; default: string }[] }[]) {
          for (const field of section.fields) {
            allFields.push({
              section: section.name,
              name: field.name,
              type: field.type,
              default: field.default,
            });
          }
        }

        // Generate var declarations
        const varLines = allFields.map(
          (f) => `var ${f.name}: ${f.type} = ${f.default}`,
        );

        // Generate setter functions
        const setterLines: string[] = [];
        for (const f of allFields) {
          setterLines.push(
            '',
            `func set_${f.name}(value: ${f.type}) -> void:`,
            `\t${f.name} = value`,
            `\tsave_data()`,
          );
        }

        // Generate load_data function
        const loadLines: string[] = [
          '',
          'func load_data() -> void:',
          '\tvar config := ConfigFile.new()',
          `\tif config.load(SAVE_PATH) == OK:`,
        ];
        for (const f of allFields) {
          loadLines.push(
            `\t\t${f.name} = config.get_value("${f.section}", "${f.name}", ${f.default})`,
          );
        }

        // Generate save_data function
        const saveLines: string[] = [
          '',
          'func save_data() -> void:',
          '\tvar config := ConfigFile.new()',
        ];
        for (const f of allFields) {
          saveLines.push(
            `\tconfig.set_value("${f.section}", "${f.name}", ${f.name})`,
          );
        }
        saveLines.push(`\tconfig.save(SAVE_PATH)`);

        const gdscript = [
          '## ConfigFile persistence manager.',
          '## Generated by godot-mcp scaffold_config_manager tool.',
          '',
          'extends Node',
          '',
          `const SAVE_PATH := "${save_path as string}"`,
          '',
          ...varLines,
          '',
          'func _ready() -> void:',
          '\tload_data()',
          ...setterLines,
          ...loadLines,
          ...saveLines,
          '',
        ].join('\n');

        // Create parent directories if they don't exist
        const fullPath = join(project_path as string, script_path as string);
        const parentDir = dirname(fullPath);
        if (!existsSync(parentDir)) {
          mkdirSync(parentDir, { recursive: true });
        }

        // Write the file
        writeFileSync(fullPath, gdscript, 'utf-8');

        // Optionally register as autoload
        const resolvedAutoloadName =
          (autoload_name as string | undefined) || toPascalCase(filenameWithoutExtension(script_path as string));
        let autoloadRegistered = false;

        if (register_autoload) {
          const opResult = await runOperation(ctx, project_path as string, 'modify_project_setting', {
            section: 'autoload',
            key: resolvedAutoloadName,
            value: '*res://' + (script_path as string),
            action: 'set',
          });
          if (!opResult.ok) {
            return toolError(`Failed to register autoload: ${opResult.error}`, [
              'The script file was written, but autoload registration failed',
              'Verify the project path is accessible',
              'Check that Godot is installed and GODOT_PATH is set',
            ]);
          }
          autoloadRegistered = true;
        }

        const result = {
          success: true,
          script_path: script_path as string,
          save_path: save_path as string,
          field_count: allFields.length,
          section_count: (sections as { name: string }[]).length,
          autoload_registered: autoloadRegistered,
          ...(autoloadRegistered ? { autoload_name: resolvedAutoloadName } : {}),
        };

        return {
          content: [
            {
              type: 'text' as const,
              text: JSON.stringify(result, null, 2),
            },
          ],
        };
      } catch (error: unknown) {
        const errorMessage =
          error instanceof Error ? error.message : 'Unknown error';
        return toolError(`Failed to scaffold ConfigManager: ${errorMessage}`, [
          'Ensure the project path is accessible',
          'Check that you have write permissions to the target directory',
          'Verify the script_path ends with .gd',
        ]);
      }
    },
  );

  // scaffold_resource_class tool
  server.registerTool(
    'scaffold_resource_class',
    {
      title: 'Scaffold Resource Class',
      description:
        'Generate a class_name Resource subclass GDScript with @export fields. Useful for creating custom data containers.',
      inputSchema: {
        project_path: z.string().describe('Path to the Godot project directory'),
        script_path: z
          .string()
          .describe(
            'Where to write the .gd file relative to project (e.g. "scripts/resources/avatar_data.gd")',
          ),
        class_name: z
          .string()
          .describe('PascalCase class name for the Resource (e.g. "AvatarData")'),
        fields: z
          .array(
            z.object({
              name: z.string(),
              type: z.string(),
              default: z.string().optional(),
            }),
          )
          .min(1)
          .describe('Export fields with name, type, and optional default value'),
      },
    },
    async ({ project_path, script_path, class_name, fields }) => {
      if (!validatePath(project_path as string) || !validatePath(script_path as string)) {
        return toolError('Invalid path', [
          'Provide valid paths without ".." or other potentially unsafe characters',
        ]);
      }

      try {
        const projectFile = join(project_path as string, 'project.godot');
        if (!existsSync(projectFile)) {
          return toolError(`Not a valid Godot project: ${project_path as string}`, [
            'Ensure the path points to a directory containing a project.godot file',
            'Use list_projects to find valid Godot projects',
          ]);
        }

        // Generate @export lines
        const exportLines = (fields as { name: string; type: string; default?: string }[]).map((f) => {
          if (f.default !== undefined && f.default !== '') {
            return `@export var ${f.name}: ${f.type} = ${f.default}`;
          }
          return `@export var ${f.name}: ${f.type}`;
        });

        const gdscript = [
          `## Custom Resource: ${class_name as string}.`,
          '## Generated by godot-mcp scaffold_resource_class tool.',
          `class_name ${class_name as string}`,
          'extends Resource',
          '',
          ...exportLines,
          '',
        ].join('\n');

        // Create parent directories if they don't exist
        const fullPath = join(project_path as string, script_path as string);
        const parentDir = dirname(fullPath);
        if (!existsSync(parentDir)) {
          mkdirSync(parentDir, { recursive: true });
        }

        // Write the file
        writeFileSync(fullPath, gdscript, 'utf-8');

        const result = {
          success: true,
          script_path: script_path as string,
          class_name: class_name as string,
          field_count: (fields as { name: string }[]).length,
        };

        return {
          content: [
            {
              type: 'text' as const,
              text: JSON.stringify(result, null, 2),
            },
          ],
        };
      } catch (error: unknown) {
        const errorMessage =
          error instanceof Error ? error.message : 'Unknown error';
        return toolError(`Failed to scaffold Resource class: ${errorMessage}`, [
          'Ensure the project path is accessible',
          'Check that you have write permissions to the target directory',
          'Verify the script_path ends with .gd',
        ]);
      }
    },
  );

  // scaffold_tests tool
  server.registerTool(
    'scaffold_tests',
    {
      title: 'Scaffold GUT Tests',
      description:
        'Read an existing GDScript file and generate a GUT test skeleton with stubs for each public method and signal assertions.',
      inputSchema: {
        project_path: z.string().describe('Path to the Godot project directory'),
        script_path: z
          .string()
          .describe(
            'Path to the existing .gd file to generate tests for, relative to project',
          ),
        test_path: z
          .string()
          .optional()
          .describe(
            'Where to write the test .gd file relative to project (default: tests/test_<filename>.gd)',
          ),
      },
    },
    async ({ project_path, script_path, test_path }) => {
      if (!validatePath(project_path as string) || !validatePath(script_path as string)) {
        return toolError('Invalid path', [
          'Provide valid paths without ".." or other potentially unsafe characters',
        ]);
      }

      try {
        const projectFile = join(project_path as string, 'project.godot');
        if (!existsSync(projectFile)) {
          return toolError(`Not a valid Godot project: ${project_path as string}`, [
            'Ensure the path points to a directory containing a project.godot file',
            'Use list_projects to find valid Godot projects',
          ]);
        }

        // Read the source script
        const sourceFullPath = join(project_path as string, script_path as string);
        if (!existsSync(sourceFullPath)) {
          return toolError(`Source script not found: ${script_path as string}`, [
            'Ensure the script_path points to an existing .gd file',
            'Use list_scripts to find available scripts',
          ]);
        }
        const sourceContent = readFileSync(sourceFullPath, 'utf-8');

        // Parse public methods (exclude names starting with _)
        const methodRegex = /^func\s+([a-zA-Z][a-zA-Z0-9_]*)\s*\(/gm;
        const methods: string[] = [];
        let methodMatch: RegExpExecArray | null;
        while ((methodMatch = methodRegex.exec(sourceContent)) !== null) {
          const name = methodMatch[1];
          if (!name.startsWith('_')) {
            methods.push(name);
          }
        }

        // Parse signals
        const signalRegex = /^signal\s+([a-zA-Z_][a-zA-Z0-9_]*)/gm;
        const signals: string[] = [];
        let signalMatch: RegExpExecArray | null;
        while ((signalMatch = signalRegex.exec(sourceContent)) !== null) {
          signals.push(signalMatch[1]);
        }

        // Derive class name from filename
        const className = toPascalCase(filenameWithoutExtension(script_path as string));

        // Determine test path
        const filename = filenameWithoutExtension(script_path as string);
        const resolvedTestPath =
          (test_path as string | undefined) || `tests/test_${filename}.gd`;

        // Generate test file
        const testLines: string[] = [
          `## GUT test skeleton for ${script_path as string}.`,
          '## Generated by godot-mcp scaffold_tests tool.',
          'extends GutTest',
          '',
          'var _sut  # system under test',
          '',
          'func before_each() -> void:',
          `\t_sut = autofree(${className}.new())`,
        ];

        // Generate method test stubs
        for (const method of methods) {
          testLines.push(
            '',
            `func test_${method}() -> void:`,
            `\t# TODO: test ${method}`,
            `\tpending("Not implemented")`,
          );
        }

        // Generate signal assertions
        for (const sig of signals) {
          testLines.push(
            '',
            `func test_has_signal_${sig}() -> void:`,
            `\tassert_true(_sut.has_signal("${sig}"), "Should have signal ${sig}")`,
          );
        }

        testLines.push('');
        const gdscript = testLines.join('\n');

        // Create parent directories if they don't exist
        const fullPath = join(project_path as string, resolvedTestPath);
        const parentDir = dirname(fullPath);
        if (!existsSync(parentDir)) {
          mkdirSync(parentDir, { recursive: true });
        }

        // Write the file
        writeFileSync(fullPath, gdscript, 'utf-8');

        const result = {
          success: true,
          test_path: resolvedTestPath,
          source_path: script_path as string,
          method_stubs: methods.length,
          signal_assertions: signals.length,
        };

        return {
          content: [
            {
              type: 'text' as const,
              text: JSON.stringify(result, null, 2),
            },
          ],
        };
      } catch (error: unknown) {
        const errorMessage =
          error instanceof Error ? error.message : 'Unknown error';
        return toolError(`Failed to scaffold tests: ${errorMessage}`, [
          'Ensure the project path is accessible',
          'Check that the source script exists and is readable',
          'Verify you have write permissions to the test directory',
        ]);
      }
    },
  );

  // scaffold_health_component tool
  server.registerTool(
    'scaffold_health_component',
    {
      title: 'Scaffold Health Component',
      description:
        'Generate a reusable health/damage component GDScript with signals, invincibility frames, damage, and healing logic.',
      inputSchema: {
        project_path: z.string().describe('Path to the Godot project directory'),
        script_path: z
          .string()
          .describe(
            'Where to write the .gd file relative to project (e.g. "scripts/components/health_component.gd")',
          ),
        max_health: z
          .number()
          .int()
          .optional()
          .default(100)
          .describe('Maximum health value (default: 100)'),
        invincibility_duration: z
          .number()
          .optional()
          .default(0.3)
          .describe('Duration of invincibility frames in seconds (default: 0.3)'),
      },
    },
    async ({ project_path, script_path, max_health, invincibility_duration }) => {
      if (!validatePath(project_path as string) || !validatePath(script_path as string)) {
        return toolError('Invalid path', [
          'Provide valid paths without ".." or other potentially unsafe characters',
        ]);
      }

      try {
        const projectFile = join(project_path as string, 'project.godot');
        if (!existsSync(projectFile)) {
          return toolError(`Not a valid Godot project: ${project_path as string}`, [
            'Ensure the path points to a directory containing a project.godot file',
            'Use list_projects to find valid Godot projects',
          ]);
        }

        const healthVal = (max_health as number) ?? 100;
        const invincVal = (invincibility_duration as number) ?? 0.3;

        const gdscript = [
          '## Health component: reusable damage/healing with invincibility frames.',
          '## Generated by godot-mcp scaffold_health_component tool.',
          'extends Node',
          '',
          'signal health_changed(current: int, maximum: int)',
          'signal damage_taken(amount: int)',
          'signal healed(amount: int)',
          'signal died',
          '',
          `@export var max_health: int = ${healthVal}`,
          `@export var invincibility_duration: float = ${invincVal}`,
          '',
          'var current_health: int',
          'var is_invincible: bool = false',
          '',
          '',
          'func _ready() -> void:',
          '\tcurrent_health = max_health',
          '',
          '',
          'func take_damage(amount: int) -> void:',
          '\tif is_invincible or current_health <= 0:',
          '\t\treturn',
          '\tcurrent_health = maxi(current_health - amount, 0)',
          '\tdamage_taken.emit(amount)',
          '\thealth_changed.emit(current_health, max_health)',
          '\tif current_health <= 0:',
          '\t\tdied.emit()',
          '\telse:',
          '\t\t_start_invincibility()',
          '',
          '',
          'func heal(amount: int) -> void:',
          '\tif current_health <= 0:',
          '\t\treturn',
          '\tvar old_health := current_health',
          '\tcurrent_health = mini(current_health + amount, max_health)',
          '\tvar actual := current_health - old_health',
          '\tif actual > 0:',
          '\t\thealed.emit(actual)',
          '\t\thealth_changed.emit(current_health, max_health)',
          '',
          '',
          'func _start_invincibility() -> void:',
          '\tis_invincible = true',
          '\tawait get_tree().create_timer(invincibility_duration).timeout',
          '\tis_invincible = false',
          '',
        ].join('\n');

        // Create parent directories if they don't exist
        const fullPath = join(project_path as string, script_path as string);
        const parentDir = dirname(fullPath);
        if (!existsSync(parentDir)) {
          mkdirSync(parentDir, { recursive: true });
        }

        // Write the file
        writeFileSync(fullPath, gdscript, 'utf-8');

        const result = {
          success: true,
          script_path: script_path as string,
          max_health: healthVal,
          invincibility_duration: invincVal,
        };

        return {
          content: [
            {
              type: 'text' as const,
              text: JSON.stringify(result, null, 2),
            },
          ],
        };
      } catch (error: unknown) {
        const errorMessage =
          error instanceof Error ? error.message : 'Unknown error';
        return toolError(`Failed to scaffold health component: ${errorMessage}`, [
          'Ensure the project path is accessible',
          'Check that you have write permissions to the target directory',
          'Verify the script_path ends with .gd',
        ]);
      }
    },
  );
}
